// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_header.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpc_5fheader_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rpc_5fheader_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rpc_5fheader_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_5fheader_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rpc_5fheader_2eproto;
namespace minirpc {
class RpcHeader;
struct RpcHeaderDefaultTypeInternal;
extern RpcHeaderDefaultTypeInternal _RpcHeader_default_instance_;
class RpcResponseHeader;
struct RpcResponseHeaderDefaultTypeInternal;
extern RpcResponseHeaderDefaultTypeInternal _RpcResponseHeader_default_instance_;
}  // namespace minirpc
PROTOBUF_NAMESPACE_OPEN
template<> ::minirpc::RpcHeader* Arena::CreateMaybeMessage<::minirpc::RpcHeader>(Arena*);
template<> ::minirpc::RpcResponseHeader* Arena::CreateMaybeMessage<::minirpc::RpcResponseHeader>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace minirpc {

enum RpcErrorCode : int {
  RPC_OK = 0,
  RPC_METHOD_NOT_FOUND = 1,
  RPC_BAD_REQUEST = 2,
  RPC_INTERNAL_ERROR = 3,
  RPC_SERVER_BUSY = 4,
  RpcErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RpcErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RpcErrorCode_IsValid(int value);
constexpr RpcErrorCode RpcErrorCode_MIN = RPC_OK;
constexpr RpcErrorCode RpcErrorCode_MAX = RPC_SERVER_BUSY;
constexpr int RpcErrorCode_ARRAYSIZE = RpcErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RpcErrorCode_descriptor();
template<typename T>
inline const std::string& RpcErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RpcErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RpcErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RpcErrorCode_descriptor(), enum_t_value);
}
inline bool RpcErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RpcErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RpcErrorCode>(
    RpcErrorCode_descriptor(), name, value);
}
// ===================================================================

class RpcHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:minirpc.RpcHeader) */ {
 public:
  inline RpcHeader() : RpcHeader(nullptr) {}
  ~RpcHeader() override;
  explicit PROTOBUF_CONSTEXPR RpcHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RpcHeader(const RpcHeader& from);
  RpcHeader(RpcHeader&& from) noexcept
    : RpcHeader() {
    *this = ::std::move(from);
  }

  inline RpcHeader& operator=(const RpcHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcHeader& operator=(RpcHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RpcHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const RpcHeader* internal_default_instance() {
    return reinterpret_cast<const RpcHeader*>(
               &_RpcHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RpcHeader& a, RpcHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(RpcHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RpcHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RpcHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RpcHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RpcHeader& from) {
    RpcHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RpcHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "minirpc.RpcHeader";
  }
  protected:
  explicit RpcHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
    kMethodNameFieldNumber = 2,
    kRequestIdFieldNumber = 4,
    kArgsSizeFieldNumber = 3,
    kMagicFieldNumber = 5,
    kVersionFieldNumber = 6,
  };
  // string service_name = 1;
  void clear_service_name();
  const std::string& service_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_service_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_service_name();
  PROTOBUF_NODISCARD std::string* release_service_name();
  void set_allocated_service_name(std::string* service_name);
  private:
  const std::string& _internal_service_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service_name(const std::string& value);
  std::string* _internal_mutable_service_name();
  public:

  // string method_name = 2;
  void clear_method_name();
  const std::string& method_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_method_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_method_name();
  PROTOBUF_NODISCARD std::string* release_method_name();
  void set_allocated_method_name(std::string* method_name);
  private:
  const std::string& _internal_method_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_method_name(const std::string& value);
  std::string* _internal_mutable_method_name();
  public:

  // uint64 request_id = 4;
  void clear_request_id();
  uint64_t request_id() const;
  void set_request_id(uint64_t value);
  private:
  uint64_t _internal_request_id() const;
  void _internal_set_request_id(uint64_t value);
  public:

  // uint32 args_size = 3;
  void clear_args_size();
  uint32_t args_size() const;
  void set_args_size(uint32_t value);
  private:
  uint32_t _internal_args_size() const;
  void _internal_set_args_size(uint32_t value);
  public:

  // uint32 magic = 5;
  void clear_magic();
  uint32_t magic() const;
  void set_magic(uint32_t value);
  private:
  uint32_t _internal_magic() const;
  void _internal_set_magic(uint32_t value);
  public:

  // uint32 version = 6;
  void clear_version();
  uint32_t version() const;
  void set_version(uint32_t value);
  private:
  uint32_t _internal_version() const;
  void _internal_set_version(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:minirpc.RpcHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_name_;
    uint64_t request_id_;
    uint32_t args_size_;
    uint32_t magic_;
    uint32_t version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fheader_2eproto;
};
// -------------------------------------------------------------------

class RpcResponseHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:minirpc.RpcResponseHeader) */ {
 public:
  inline RpcResponseHeader() : RpcResponseHeader(nullptr) {}
  ~RpcResponseHeader() override;
  explicit PROTOBUF_CONSTEXPR RpcResponseHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RpcResponseHeader(const RpcResponseHeader& from);
  RpcResponseHeader(RpcResponseHeader&& from) noexcept
    : RpcResponseHeader() {
    *this = ::std::move(from);
  }

  inline RpcResponseHeader& operator=(const RpcResponseHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcResponseHeader& operator=(RpcResponseHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RpcResponseHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const RpcResponseHeader* internal_default_instance() {
    return reinterpret_cast<const RpcResponseHeader*>(
               &_RpcResponseHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RpcResponseHeader& a, RpcResponseHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(RpcResponseHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcResponseHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RpcResponseHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RpcResponseHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RpcResponseHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RpcResponseHeader& from) {
    RpcResponseHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RpcResponseHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "minirpc.RpcResponseHeader";
  }
  protected:
  explicit RpcResponseHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 3,
    kRequestIdFieldNumber = 1,
    kErrorCodeFieldNumber = 2,
    kPayloadSizeFieldNumber = 4,
    kMagicFieldNumber = 5,
    kVersionFieldNumber = 6,
  };
  // string error_message = 3;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // uint64 request_id = 1;
  void clear_request_id();
  uint64_t request_id() const;
  void set_request_id(uint64_t value);
  private:
  uint64_t _internal_request_id() const;
  void _internal_set_request_id(uint64_t value);
  public:

  // .minirpc.RpcErrorCode error_code = 2;
  void clear_error_code();
  ::minirpc::RpcErrorCode error_code() const;
  void set_error_code(::minirpc::RpcErrorCode value);
  private:
  ::minirpc::RpcErrorCode _internal_error_code() const;
  void _internal_set_error_code(::minirpc::RpcErrorCode value);
  public:

  // uint32 payload_size = 4;
  void clear_payload_size();
  uint32_t payload_size() const;
  void set_payload_size(uint32_t value);
  private:
  uint32_t _internal_payload_size() const;
  void _internal_set_payload_size(uint32_t value);
  public:

  // uint32 magic = 5;
  void clear_magic();
  uint32_t magic() const;
  void set_magic(uint32_t value);
  private:
  uint32_t _internal_magic() const;
  void _internal_set_magic(uint32_t value);
  public:

  // uint32 version = 6;
  void clear_version();
  uint32_t version() const;
  void set_version(uint32_t value);
  private:
  uint32_t _internal_version() const;
  void _internal_set_version(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:minirpc.RpcResponseHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    uint64_t request_id_;
    int error_code_;
    uint32_t payload_size_;
    uint32_t magic_;
    uint32_t version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fheader_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RpcHeader

// string service_name = 1;
inline void RpcHeader::clear_service_name() {
  _impl_.service_name_.ClearToEmpty();
}
inline const std::string& RpcHeader::service_name() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcHeader.service_name)
  return _internal_service_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RpcHeader::set_service_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.service_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:minirpc.RpcHeader.service_name)
}
inline std::string* RpcHeader::mutable_service_name() {
  std::string* _s = _internal_mutable_service_name();
  // @@protoc_insertion_point(field_mutable:minirpc.RpcHeader.service_name)
  return _s;
}
inline const std::string& RpcHeader::_internal_service_name() const {
  return _impl_.service_name_.Get();
}
inline void RpcHeader::_internal_set_service_name(const std::string& value) {
  
  _impl_.service_name_.Set(value, GetArenaForAllocation());
}
inline std::string* RpcHeader::_internal_mutable_service_name() {
  
  return _impl_.service_name_.Mutable(GetArenaForAllocation());
}
inline std::string* RpcHeader::release_service_name() {
  // @@protoc_insertion_point(field_release:minirpc.RpcHeader.service_name)
  return _impl_.service_name_.Release();
}
inline void RpcHeader::set_allocated_service_name(std::string* service_name) {
  if (service_name != nullptr) {
    
  } else {
    
  }
  _impl_.service_name_.SetAllocated(service_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.service_name_.IsDefault()) {
    _impl_.service_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:minirpc.RpcHeader.service_name)
}

// string method_name = 2;
inline void RpcHeader::clear_method_name() {
  _impl_.method_name_.ClearToEmpty();
}
inline const std::string& RpcHeader::method_name() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcHeader.method_name)
  return _internal_method_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RpcHeader::set_method_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.method_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:minirpc.RpcHeader.method_name)
}
inline std::string* RpcHeader::mutable_method_name() {
  std::string* _s = _internal_mutable_method_name();
  // @@protoc_insertion_point(field_mutable:minirpc.RpcHeader.method_name)
  return _s;
}
inline const std::string& RpcHeader::_internal_method_name() const {
  return _impl_.method_name_.Get();
}
inline void RpcHeader::_internal_set_method_name(const std::string& value) {
  
  _impl_.method_name_.Set(value, GetArenaForAllocation());
}
inline std::string* RpcHeader::_internal_mutable_method_name() {
  
  return _impl_.method_name_.Mutable(GetArenaForAllocation());
}
inline std::string* RpcHeader::release_method_name() {
  // @@protoc_insertion_point(field_release:minirpc.RpcHeader.method_name)
  return _impl_.method_name_.Release();
}
inline void RpcHeader::set_allocated_method_name(std::string* method_name) {
  if (method_name != nullptr) {
    
  } else {
    
  }
  _impl_.method_name_.SetAllocated(method_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.method_name_.IsDefault()) {
    _impl_.method_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:minirpc.RpcHeader.method_name)
}

// uint32 args_size = 3;
inline void RpcHeader::clear_args_size() {
  _impl_.args_size_ = 0u;
}
inline uint32_t RpcHeader::_internal_args_size() const {
  return _impl_.args_size_;
}
inline uint32_t RpcHeader::args_size() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcHeader.args_size)
  return _internal_args_size();
}
inline void RpcHeader::_internal_set_args_size(uint32_t value) {
  
  _impl_.args_size_ = value;
}
inline void RpcHeader::set_args_size(uint32_t value) {
  _internal_set_args_size(value);
  // @@protoc_insertion_point(field_set:minirpc.RpcHeader.args_size)
}

// uint64 request_id = 4;
inline void RpcHeader::clear_request_id() {
  _impl_.request_id_ = uint64_t{0u};
}
inline uint64_t RpcHeader::_internal_request_id() const {
  return _impl_.request_id_;
}
inline uint64_t RpcHeader::request_id() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcHeader.request_id)
  return _internal_request_id();
}
inline void RpcHeader::_internal_set_request_id(uint64_t value) {
  
  _impl_.request_id_ = value;
}
inline void RpcHeader::set_request_id(uint64_t value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:minirpc.RpcHeader.request_id)
}

// uint32 magic = 5;
inline void RpcHeader::clear_magic() {
  _impl_.magic_ = 0u;
}
inline uint32_t RpcHeader::_internal_magic() const {
  return _impl_.magic_;
}
inline uint32_t RpcHeader::magic() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcHeader.magic)
  return _internal_magic();
}
inline void RpcHeader::_internal_set_magic(uint32_t value) {
  
  _impl_.magic_ = value;
}
inline void RpcHeader::set_magic(uint32_t value) {
  _internal_set_magic(value);
  // @@protoc_insertion_point(field_set:minirpc.RpcHeader.magic)
}

// uint32 version = 6;
inline void RpcHeader::clear_version() {
  _impl_.version_ = 0u;
}
inline uint32_t RpcHeader::_internal_version() const {
  return _impl_.version_;
}
inline uint32_t RpcHeader::version() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcHeader.version)
  return _internal_version();
}
inline void RpcHeader::_internal_set_version(uint32_t value) {
  
  _impl_.version_ = value;
}
inline void RpcHeader::set_version(uint32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:minirpc.RpcHeader.version)
}

// -------------------------------------------------------------------

// RpcResponseHeader

// uint64 request_id = 1;
inline void RpcResponseHeader::clear_request_id() {
  _impl_.request_id_ = uint64_t{0u};
}
inline uint64_t RpcResponseHeader::_internal_request_id() const {
  return _impl_.request_id_;
}
inline uint64_t RpcResponseHeader::request_id() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcResponseHeader.request_id)
  return _internal_request_id();
}
inline void RpcResponseHeader::_internal_set_request_id(uint64_t value) {
  
  _impl_.request_id_ = value;
}
inline void RpcResponseHeader::set_request_id(uint64_t value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:minirpc.RpcResponseHeader.request_id)
}

// .minirpc.RpcErrorCode error_code = 2;
inline void RpcResponseHeader::clear_error_code() {
  _impl_.error_code_ = 0;
}
inline ::minirpc::RpcErrorCode RpcResponseHeader::_internal_error_code() const {
  return static_cast< ::minirpc::RpcErrorCode >(_impl_.error_code_);
}
inline ::minirpc::RpcErrorCode RpcResponseHeader::error_code() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcResponseHeader.error_code)
  return _internal_error_code();
}
inline void RpcResponseHeader::_internal_set_error_code(::minirpc::RpcErrorCode value) {
  
  _impl_.error_code_ = value;
}
inline void RpcResponseHeader::set_error_code(::minirpc::RpcErrorCode value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:minirpc.RpcResponseHeader.error_code)
}

// string error_message = 3;
inline void RpcResponseHeader::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& RpcResponseHeader::error_message() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcResponseHeader.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RpcResponseHeader::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:minirpc.RpcResponseHeader.error_message)
}
inline std::string* RpcResponseHeader::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:minirpc.RpcResponseHeader.error_message)
  return _s;
}
inline const std::string& RpcResponseHeader::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void RpcResponseHeader::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* RpcResponseHeader::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* RpcResponseHeader::release_error_message() {
  // @@protoc_insertion_point(field_release:minirpc.RpcResponseHeader.error_message)
  return _impl_.error_message_.Release();
}
inline void RpcResponseHeader::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:minirpc.RpcResponseHeader.error_message)
}

// uint32 payload_size = 4;
inline void RpcResponseHeader::clear_payload_size() {
  _impl_.payload_size_ = 0u;
}
inline uint32_t RpcResponseHeader::_internal_payload_size() const {
  return _impl_.payload_size_;
}
inline uint32_t RpcResponseHeader::payload_size() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcResponseHeader.payload_size)
  return _internal_payload_size();
}
inline void RpcResponseHeader::_internal_set_payload_size(uint32_t value) {
  
  _impl_.payload_size_ = value;
}
inline void RpcResponseHeader::set_payload_size(uint32_t value) {
  _internal_set_payload_size(value);
  // @@protoc_insertion_point(field_set:minirpc.RpcResponseHeader.payload_size)
}

// uint32 magic = 5;
inline void RpcResponseHeader::clear_magic() {
  _impl_.magic_ = 0u;
}
inline uint32_t RpcResponseHeader::_internal_magic() const {
  return _impl_.magic_;
}
inline uint32_t RpcResponseHeader::magic() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcResponseHeader.magic)
  return _internal_magic();
}
inline void RpcResponseHeader::_internal_set_magic(uint32_t value) {
  
  _impl_.magic_ = value;
}
inline void RpcResponseHeader::set_magic(uint32_t value) {
  _internal_set_magic(value);
  // @@protoc_insertion_point(field_set:minirpc.RpcResponseHeader.magic)
}

// uint32 version = 6;
inline void RpcResponseHeader::clear_version() {
  _impl_.version_ = 0u;
}
inline uint32_t RpcResponseHeader::_internal_version() const {
  return _impl_.version_;
}
inline uint32_t RpcResponseHeader::version() const {
  // @@protoc_insertion_point(field_get:minirpc.RpcResponseHeader.version)
  return _internal_version();
}
inline void RpcResponseHeader::_internal_set_version(uint32_t value) {
  
  _impl_.version_ = value;
}
inline void RpcResponseHeader::set_version(uint32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:minirpc.RpcResponseHeader.version)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace minirpc

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::minirpc::RpcErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::minirpc::RpcErrorCode>() {
  return ::minirpc::RpcErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rpc_5fheader_2eproto
